(
    SELECT_QUANTITY,
    TYPING_RECHARGE_PUBG_ID,
    SELECT_RECHARGE_QUANTITY,
    SELECTING_PAYMENT_METHOD,
    AMOUNT_INPUT
) = range(5)

CONFIRM_PURCHASE = range(6, 7)
CONFIRM_RECHARGE_PURCHASE = 8