(
    SELECT_QUANTITY,
    TYPING_RECHARGE_PUBG_ID,
    SELECT_RECHARGE_QUANTITY,
    SELECTING_PAYMENT_METHOD,
    AMOUNT_INPUT
) = range(5)

CONFIRM_PURCHASE = range(6, 7)
CONFIRM_RECHARGE_PURCHASE = 8

SELECT_MANUAL_QUANTITY = 101
CONFIRM_MANUAL_PURCHASE = 102

BEP20_AMOUNT_INPUT = 201
BEP20_AMOUNT_CONFIRM = 202

TYPING_MANUAL_PUBG_ID =301