# Generated by Django 5.2.1 on 2025-05-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_paymenttransaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
