# Generated by Django 5.2.1 on 2025-05-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_telegramuser_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
