# Generated by Django 5.2.1 on 2025-05-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_telegramuser_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='tx_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
