# Generated by Django 5.2.1 on 2025-06-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paymenttransaction_tx_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='topuptransaction',
            name='tx_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
