# Generated by Django 5.2.1 on 2025-05-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rechargecategory_product_recharge_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pubg_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pubg_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
