# Generated by Django 5.2.1 on 2026-01-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_paymenttransaction_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopUpTransaction',
            new_name='Transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_received',
            new_name='amount',
        ),
    ]
