# Generated by Django 5.2.1 on 2026-02-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='announcements/files/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/images/'),
        ),
    ]
