# Generated by Django 5.2.1 on 2026-05-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_announcement_attachment_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='broadcasted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_broadcasted',
            field=models.BooleanField(default=False),
        ),
    ]
