# Generated by Django 5.2.1 on 2026-02-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_announcement_attachment_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercode',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='core.supplier'),
        ),
    ]
