# Generated by Django 5.2.1 on 2026-05-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvouchercode',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
