# Generated by Django 5.2.1 on 2026-05-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_uploadvouchercode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Admin Pending', 'Admin Pending'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
