# Generated by Django 5.2.1 on 2026-05-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_response_text',
            field=models.TextField(blank=True, help_text='Message sent to user upon approval', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_file',
            field=models.FileField(blank=True, help_text='File sent to user', null=True, upload_to='deliveries/'),
        ),
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection', null=True),
        ),
    ]
