# Generated by Django 5.2.1 on 2026-05-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_order_admin_response_text_order_delivery_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Payment Gateway', 'Payment Gateway')], default='Payment Gateway', max_length=20),
        ),
    ]
