# Generated by Django 5.2.1 on 2026-05-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_product_is_manual_product_is_normal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_normal',
            field=models.BooleanField(default=True),
        ),
    ]
